name: Run unit tests and publish samples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install and test
      run: |
        npm ci
        npm run test:unit
    - name: build samples
      run: |
        npx vue-cli-service build
    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
      env:
        CI: true
